eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8084/realms/springboot-microservices
management.zipkin.tracing.endpoint=http://zipkin:9411
app.eureka-server=discovery-server