spring.application.name=order-service
server.port=0

spring.data.mongo.uri=mongodb://test:test@localhost:27017/local

##Eureka client config
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
## This is to create a random instance id to allow multiple instances register with eureka
eureka.instance.instance-id=${spring.application.name}:${random.int(1000)}


